apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
  clusterIP: None  # Headless service to use DNS resolution

---

apiVersion: v1
kind: Service
metadata:
  name: lightbox-posts-app
spec:
  type: NodePort
  selector:
    app: lightbox-posts-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000  # Django will be running on port 8000 in the container
      nodePort: 30000